# nixpacks.toml (Versi Final yang Benar)

[phases.setup]
# Kuncinya adalah menambahkan "php" dan "composer" ke dalam daftar.
# Sesuaikan versi PHP jika perlu (misal: php83, php83Extensions).
nixPkgs = ["php82", "composer", "php82Extensions.pgsql", "php82Extensions.pdo_pgsql", "php82Extensions.intl"]