# nixpacks.toml

[phases.setup]
# Menambahkan Node.js kembali ke daftar, beserta ekstensi PHP yang dibutuhkan
nixPkgs = [
    "php",
    "phpPackages.composer",
    "nodejs_18",
    "phpExtensions.pdo_pgsql",
    "phpExtensions.bcmath"
]